# Generated by go2rpm 1.5.0
%bcond_without check
%define build_timestamp %(date +"%Y%m%d%H%M")

# https://github.com/argoproj/argo-workflows
%global goipath         github.com/argoproj/argo-workflows
# renovate: datasource=github-releases depName=argoproj/argo-workflows
Version: 3.2.3

%gometa

%global common_description %{expand:
Workflow engine for Kubernetes.}

%global golicenses      LICENSE
%global godocs          docs examples CHANGELOG.md README.md SECURITY.md\\\
                        USERS.md community/README.md hack/changelog.sh\\\
                        hack/custom-boilerplate.go.txt hack/release-notes.md\\\
                        manifests/README.md\\\
                        manifests/base/crds/full/README.md\\\
                        manifests/base/crds/minimal/README.md\\\
                        pkg/apiclient/clusterworkflowtemplate/testy.txt\\\
                        sdks/CONTRIBUTING.md sdks/java/README.md docs\\\
                        ui/README.md

Name:           %{goname}
Release:        %{build_timestamp}%{?dist}
Summary:        Workflow engine for Kubernetes

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires: git

Provides:  golang(cloud.google.com/go/storage)
Provides:  golang(github.com/aliyun/aliyun-oss-go-sdk/oss)
Provides:  golang(github.com/antonmedv/expr)
Provides:  golang(github.com/antonmedv/expr/file)
Provides:  golang(github.com/antonmedv/expr/parser/lexer)
Provides:  golang(github.com/argoproj-labs/argo-dataflow/api/v1alpha1)
Provides:  golang(github.com/argoproj/argo-events/pkg/apis/eventsource/v1alpha1)
Provides:  golang(github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1)
Provides:  golang(github.com/argoproj/argo-events/pkg/client/eventsource/clientset/versioned)
Provides:  golang(github.com/argoproj/argo-events/pkg/client/sensor/clientset/versioned)
Provides:  golang(github.com/argoproj/pkg/cli)
Provides:  golang(github.com/argoproj/pkg/errors)
Provides:  golang(github.com/argoproj/pkg/exec)
Provides:  golang(github.com/argoproj/pkg/expr)
Provides:  golang(github.com/argoproj/pkg/file)
Provides:  golang(github.com/argoproj/pkg/grpc/http)
Provides:  golang(github.com/argoproj/pkg/humanize)
Provides:  golang(github.com/argoproj/pkg/json)
Provides:  golang(github.com/argoproj/pkg/kube/cli)
Provides:  golang(github.com/argoproj/pkg/kube/errors)
Provides:  golang(github.com/argoproj/pkg/rand)
Provides:  golang(github.com/argoproj/pkg/s3)
Provides:  golang(github.com/argoproj/pkg/stats)
Provides:  golang(github.com/argoproj/pkg/strftime)
Provides:  golang(github.com/argoproj/pkg/sync)
Provides:  golang(github.com/argoproj/pkg/time)
Provides:  golang(github.com/blushft/go-diagrams/diagram)
Provides:  golang(github.com/blushft/go-diagrams/nodes/apps)
Provides:  golang(github.com/blushft/go-diagrams/nodes/gcp)
Provides:  golang(github.com/blushft/go-diagrams/nodes/generic)
Provides:  golang(github.com/blushft/go-diagrams/nodes/k8s)
Provides:  golang(github.com/blushft/go-diagrams/nodes/programming)
Provides:  golang(github.com/blushft/go-diagrams/nodes/saas)
Provides:  golang(github.com/colinmarc/hdfs)
Provides:  golang(github.com/coreos/go-oidc/v3/oidc)
Provides:  golang(github.com/doublerebel/bellows)
Provides:  golang(github.com/evanphx/json-patch)
Provides:  golang(github.com/go-openapi/jsonreference)
Provides:  golang(github.com/go-openapi/spec)
Provides:  golang(github.com/go-python/gpython/builtin)
Provides:  golang(github.com/go-python/gpython/compile)
Provides:  golang(github.com/go-python/gpython/py)
Provides:  golang(github.com/go-python/gpython/vm)
Provides:  golang(github.com/go-sql-driver/mysql)
Provides:  golang(github.com/gogo/protobuf/proto)
Provides:  golang(github.com/gogo/protobuf/sortkeys)
Provides:  golang(github.com/golang/protobuf/descriptor)
Provides:  golang(github.com/golang/protobuf/proto)
Provides:  golang(github.com/gorilla/handlers)
Provides:  golang(github.com/gorilla/websocket)
Provides:  golang(github.com/grpc-ecosystem/go-grpc-middleware)
Provides:  golang(github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus)
Provides:  golang(github.com/grpc-ecosystem/go-grpc-prometheus)
Provides:  golang(github.com/grpc-ecosystem/grpc-gateway/runtime)
Provides:  golang(github.com/grpc-ecosystem/grpc-gateway/utilities)
Provides:  golang(github.com/klauspost/pgzip)
Provides:  golang(github.com/Knetic/govaluate)
Provides:  golang(github.com/Masterminds/sprig/v3)
Provides:  golang(github.com/minio/minio-go/v7)
Provides:  golang(github.com/mitchellh/go-ps)
Provides:  golang(github.com/pkg/errors)
Provides:  golang(github.com/prometheus/client_golang/prometheus)
Provides:  golang(github.com/prometheus/client_golang/prometheus/promhttp)
Provides:  golang(github.com/prometheus/common/model)
Provides:  golang(github.com/robfig/cron/v3)
Provides:  golang(github.com/sirupsen/logrus)
Provides:  golang(github.com/skratchdot/open-golang/open)
Provides:  golang(github.com/soheilhy/cmux)
Provides:  golang(github.com/spf13/cobra)
Provides:  golang(github.com/spf13/cobra/doc)
Provides:  golang(github.com/spf13/pflag)
Provides:  golang(github.com/spf13/viper)
Provides:  golang(github.com/stretchr/testify/assert)
Provides:  golang(github.com/stretchr/testify/mock)
Provides:  golang(github.com/stretchr/testify/suite)
Provides:  golang(github.com/tidwall/gjson)
Provides:  golang(github.com/TwinProduction/go-color)
Provides:  golang(github.com/valyala/fasttemplate)
Provides:  golang(github.com/xeipuuv/gojsonschema)
Provides:  golang(golang.org/x/crypto/ssh)
Provides:  golang(golang.org/x/net/context)
Provides:  golang(golang.org/x/oauth2)
Provides:  golang(golang.org/x/oauth2/google)
Provides:  golang(golang.org/x/sync/semaphore)
Provides:  golang(golang.org/x/time/rate)
Provides:  golang(google.golang.org/api/googleapi)
Provides:  golang(google.golang.org/api/iterator)
Provides:  golang(google.golang.org/api/option)
Provides:  golang(google.golang.org/genproto/googleapis/api/annotations)
Provides:  golang(google.golang.org/grpc)
Provides:  golang(google.golang.org/grpc/codes)
Provides:  golang(google.golang.org/grpc/credentials)
Provides:  golang(google.golang.org/grpc/grpclog)
Provides:  golang(google.golang.org/grpc/metadata)
Provides:  golang(google.golang.org/grpc/status)
Provides:  golang(gopkg.in/go-playground/webhooks.v5/bitbucket)
Provides:  golang(gopkg.in/go-playground/webhooks.v5/bitbucket-server)
Provides:  golang(gopkg.in/go-playground/webhooks.v5/github)
Provides:  golang(gopkg.in/go-playground/webhooks.v5/gitlab)
Provides:  golang(gopkg.in/jcmturner/gokrb5.v5/client)
Provides:  golang(gopkg.in/jcmturner/gokrb5.v5/config)
Provides:  golang(gopkg.in/jcmturner/gokrb5.v5/credentials)
Provides:  golang(gopkg.in/jcmturner/gokrb5.v5/keytab)
Provides:  golang(gopkg.in/square/go-jose.v2)
Provides:  golang(gopkg.in/square/go-jose.v2/jwt)
Provides:  golang(gopkg.in/src-d/go-git.v4)
Provides:  golang(gopkg.in/src-d/go-git.v4/config)
Provides:  golang(gopkg.in/src-d/go-git.v4/plumbing)
Provides:  golang(gopkg.in/src-d/go-git.v4/plumbing/transport)
Provides:  golang(gopkg.in/src-d/go-git.v4/plumbing/transport/http)
Provides:  golang(gopkg.in/src-d/go-git.v4/plumbing/transport/ssh)
Provides:  golang(k8s.io/api/authorization/v1)
Provides:  golang(k8s.io/api/core/v1)
Provides:  golang(k8s.io/api/policy/v1beta1)
Provides:  golang(k8s.io/apimachinery/pkg/api/errors)
Provides:  golang(k8s.io/apimachinery/pkg/api/meta)
Provides:  golang(k8s.io/apimachinery/pkg/api/resource)
Provides:  golang(k8s.io/apimachinery/pkg/apis/meta/v1)
Provides:  golang(k8s.io/apimachinery/pkg/apis/meta/v1/unstructured)
Provides:  golang(k8s.io/apimachinery/pkg/fields)
Provides:  golang(k8s.io/apimachinery/pkg/labels)
Provides:  golang(k8s.io/apimachinery/pkg/runtime)
Provides:  golang(k8s.io/apimachinery/pkg/runtime/schema)
Provides:  golang(k8s.io/apimachinery/pkg/runtime/serializer)
Provides:  golang(k8s.io/apimachinery/pkg/selection)
Provides:  golang(k8s.io/apimachinery/pkg/types)
Provides:  golang(k8s.io/apimachinery/pkg/util/clock)
Provides:  golang(k8s.io/apimachinery/pkg/util/intstr)
Provides:  golang(k8s.io/apimachinery/pkg/util/runtime)
Provides:  golang(k8s.io/apimachinery/pkg/util/strategicpatch)
Provides:  golang(k8s.io/apimachinery/pkg/util/validation)
Provides:  golang(k8s.io/apimachinery/pkg/util/wait)
Provides:  golang(k8s.io/apimachinery/pkg/watch)
Provides:  golang(k8s.io/client-go/discovery)
Provides:  golang(k8s.io/client-go/discovery/fake)
Provides:  golang(k8s.io/client-go/dynamic)
Provides:  golang(k8s.io/client-go/dynamic/dynamicinformer)
Provides:  golang(k8s.io/client-go/informers)
Provides:  golang(k8s.io/client-go/informers/core/v1)
Provides:  golang(k8s.io/client-go/informers/internalinterfaces)
Provides:  golang(k8s.io/client-go/kubernetes)
Provides:  golang(k8s.io/client-go/kubernetes/scheme)
Provides:  golang(k8s.io/client-go/kubernetes/typed/core/v1)
Provides:  golang(k8s.io/client-go/pkg/apis/clientauthentication)
Provides:  golang(k8s.io/client-go/plugin/pkg/client/auth)
Provides:  golang(k8s.io/client-go/plugin/pkg/client/auth/exec)
Provides:  golang(k8s.io/client-go/rest)
Provides:  golang(k8s.io/client-go/testing)
Provides:  golang(k8s.io/client-go/tools/cache)
Provides:  golang(k8s.io/client-go/tools/clientcmd)
Provides:  golang(k8s.io/client-go/tools/clientcmd/api)
Provides:  golang(k8s.io/client-go/tools/leaderelection)
Provides:  golang(k8s.io/client-go/tools/leaderelection/resourcelock)
Provides:  golang(k8s.io/client-go/tools/record)
Provides:  golang(k8s.io/client-go/tools/remotecommand)
Provides:  golang(k8s.io/client-go/tools/watch)
Provides:  golang(k8s.io/client-go/transport)
Provides:  golang(k8s.io/client-go/util/flowcontrol)
Provides:  golang(k8s.io/client-go/util/retry)
Provides:  golang(k8s.io/client-go/util/workqueue)
Provides:  golang(k8s.io/klog/v2)
Provides:  golang(k8s.io/kube-openapi/pkg/common)
Provides:  golang(k8s.io/utils/env)
Provides:  golang(k8s.io/utils/pointer)
Provides:  golang(sigs.k8s.io/yaml)
Provides:  golang(upper.io/db.v3)
Provides:  golang(upper.io/db.v3/lib/sqlbuilder)
Provides:  golang(upper.io/db.v3/mysql)
Provides:  golang(upper.io/db.v3/postgresql)

%description
%{common_description}

%gopkg

%prep
%goprep -k

%build
go mod vendor -v
go mod verify
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
for cmd in hack/diagram hack hack/swagger hack/cli hack/jsonschema; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%files
%license LICENSE
%doc docs examples CHANGELOG.md README.md SECURITY.md USERS.md
%doc community/README.md hack/changelog.sh hack/custom-boilerplate.go.txt
%doc hack/release-notes.md manifests/README.md
%doc manifests/base/crds/full/README.md manifests/base/crds/minimal/README.md
%doc pkg/apiclient/clusterworkflowtemplate/testy.txt sdks/CONTRIBUTING.md
%doc sdks/java/README.md docs ui/README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
